export const TOGGLEDARKMODE = "TOGGLEDARKMODE";
export const STATISTICS = "STATISTICS";
export const CHANGE_WALLET = "CHANGE_WALLET";
export const SELECT_CHAIN = "SELECT_CHAIN";
export const TOKEN_LIST = "TOKEN_LIST";
export const ADD_TOKEN = "ADD_TOKEN";
export const REMOVE_TOKEN = "REMOVE_TOKEN";